name: branches
description: A CLI application that provides interactive vcs branch management.
version: 1.0.0

environment:
  sdk: ^3.9.0

dependencies:
  process_run: ^1.2.4
  ansi_styles: ^0.3.2+1
  args: ^2.4.2
  meta: ^1.16.0
  collection: ^1.19.1
  dart_console: ^4.1.2
  equatable: ^2.0.7
  async: ^2.13.0
  http: ^1.5.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  test_process: ^2.1.0
